const TODAY = new Date().toISOString().substring(0, 10);
export const components: any = {
  // !CPU
  cpu: [
    { key: "type", inputType: "text", defaultValue: "cpu", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Intel", "Amd"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },
    { key: "total_cores", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "number_of_performance_cores", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "number_of_efficient_cores", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "total_threads", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "boost_clock", inputType: "number", defaultValue: "", readOnly: false },
    { key: "cache", inputType: "number", defaultValue: "", readOnly: false },
    {
      key: "integrated_graphics",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Yes", "No"],
    },
    {
      key: "socket",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "LGA1700", "AM4"],
    },
    {
      key: "architecture",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Alder Lake", "Zen 3"],
    },
    { key: "launch_date", inputType: "date", defaultValue: TODAY, readOnly: false },
    {
      key: "stock_cooler",
      inputType: "select",
      defaultValue: "no",
      readOnly: false,
      options: ["", "Yes", "No"],
    },
    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
    { key: "keywords", inputType: "text", defaultValue: "", readOnly: false },
  ],
  // !MOBO
  mobo: [
    { key: "type", inputType: "text", defaultValue: "mobo", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "AORUS", "ASRock", "Asus", "MSI", "NZXT"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },
    {
      key: "platform",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "intel", "amd"],
    },
    {
      key: "socket",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "LGA1700", "AM4"],
    },
    {
      key: "chipset",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Z690", "H670", "B660", "H610", "LGA1200", "X570", "B550", "A520"],
    },
    {
      key: "ram_type",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "DDR5", "DDR4"],
    },
    { key: "memory_speed_max", inputType: "number", defaultValue: "", readOnly: false },
    {
      key: "lan_speed_max",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "1G", "2.5G", "10G"],
    },
    {
      key: "max_memory",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "32 GB", "64 GB", "128 GB"],
    },
    {
      key: "form_factor",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "EATX", "ATX", "Micro ATX", "Mini ITX"],
    },
    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
  // !RAM
  ram: [
    { key: "type", inputType: "text", defaultValue: "ram", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Corsair", "Kingston"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },

    {
      key: "memory_size",
      inputType: "select",
      defaultValue: 0,
      readOnly: false,
      options: [0, 8, 16, 32, 64, 128],
    },
    {
      key: "speed",
      inputType: "select",
      defaultValue: 0,
      readOnly: false,
      options: [0, 3600, 3466, 3200, 3000, 2666],
    },
    {
      key: "ram_type",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "DDR5", "DDR4"],
    },
    {
      key: "CAS_latency",
      inputType: "select",
      defaultValue: 0,
      readOnly: false,
      options: [0, 18, 17, 16, 15, 13],
    },
    //     { key: "timing", inputType: "text", defaultValue: "", readOnly: false },

    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    {
      key: "power",
      inputType: "select",
      defaultValue: 0,
      readOnly: false,
      options: [0, 3, 6, 12, 24, 48],
    },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
  // !GPU
  gpu: [
    { key: "type", inputType: "text", defaultValue: "gpu", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Asus", "MSI"],
      //       options: ["", "AORUS", "Asus", "EVGA", "MSI", "Zotac"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },

    {
      key: "memory",
      inputType: "select",
      defaultValue: 0,
      readOnly: false,
      options: [0, 4, 8, 10, 12, 16, 24],
    },
    {
      key: "memory_type",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "GDDR5", "GDDR5X", "GDDR6", "GDDR6X"],
    },
    { key: "gpu_boost_clock", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "length", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "benchmark", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "launch_date", inputType: "text", defaultValue: "", readOnly: false },

    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
  // !POWER
  power: [
    { key: "type", inputType: "text", defaultValue: "power", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Cooler Master", "Corsair", "EVGA", "Gigabyte", "SeaSonic"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },

    {
      key: "efficiency_rating",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "80+ Titanium", "80+ Platinum", "80+ Gold", "80+ Bronze", "80+"],
    },
    { key: "wattage", inputType: "number", defaultValue: 0, readOnly: false },
    {
      key: "form_factor",
      inputType: "select",
      defaultValue: "ATX",
      readOnly: false,
      options: ["ATX", "SFX"],
    },

    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
  // !CASE
  case: [
    { key: "type", inputType: "text", defaultValue: "case", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Cooler Master", "Corsair", "Fractal Design", "Lian Li", "NZXT"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },

    { key: "length", inputType: "number", defaultValue: 0, readOnly: false },
    {
      key: "form_factor",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "FULL TOWER", "MID TOWER", "SMALL FORM"],
    },
    {
      key: "PSU",
      inputType: "select",
      defaultValue: "no",
      readOnly: false,
      options: ["no", "yes"],
    },

    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
  // !NVME
  nvme: [
    { key: "type", inputType: "text", defaultValue: "nvme", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Crucial", "Samsung", "Seagate", "Western Digital"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },

    { key: "capacity", inputType: "text", defaultValue: "", readOnly: false },
    { key: "read", inputType: "text", defaultValue: "", readOnly: false },
    { key: "write", inputType: "text", defaultValue: "", readOnly: false },
    { key: "terabytes_written", inputType: "text", defaultValue: "", readOnly: false },

    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
  // !SSD
  ssd: [
    { key: "type", inputType: "text", defaultValue: "ssd", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Crucial", "Samsung", "Seagate", "Western Digital"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },

    { key: "capacity", inputType: "text", defaultValue: "", readOnly: false },
    { key: "read", inputType: "text", defaultValue: "", readOnly: false },
    { key: "write", inputType: "text", defaultValue: "", readOnly: false },
    { key: "terabytes_written", inputType: "text", defaultValue: "", readOnly: false },

    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
  // !SSD
  hdd: [
    { key: "type", inputType: "text", defaultValue: "hdd", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Seagate", "TOSHIBA", "Western Digital"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },

    { key: "capacity", inputType: "text", defaultValue: "", readOnly: false },
    {
      key: "rpm",
      inputType: "select",
      defaultValue: 0,
      readOnly: false,
      options: ["", 5400, 7200],
    },
    { key: "cache", inputType: "text", defaultValue: "", readOnly: false },

    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
  // !COOLER
  cooler: [
    { key: "type", inputType: "text", defaultValue: "cooler", readOnly: true },
    {
      key: "manufacturer",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "ARCTIC", "Cooler Master", "Corsair", "Noctua", "NZXT"],
    },
    { key: "model", inputType: "text", defaultValue: "", readOnly: false },

    { key: "compatibility", inputType: "text", defaultValue: "", readOnly: false },
    {
      key: "cooler_type",
      inputType: "select",
      defaultValue: "",
      readOnly: false,
      options: ["", "Air", "Liquid"],
    },
    { key: "noise_level", inputType: "text", defaultValue: "", readOnly: false },

    { key: "price", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "power", inputType: "number", defaultValue: 0, readOnly: false },
    { key: "quantity", inputType: "number", defaultValue: 1, readOnly: true },
    { key: "error", inputType: "text", defaultValue: "false", readOnly: true },
    { key: "warning", inputType: "text", defaultValue: "none", readOnly: true },
    {
      key: "available",
      inputType: "select",
      defaultValue: "true",
      readOnly: false,
      options: ["true", "false"],
    },
  ],
};
